
<?php
// api/data_menus.php
return [
    ['monitor', 'কিওয়ার্ড মনিটর', null, 1],
    ['report_generator', 'রিপোর্ট জেনারেটর', null, 2],
    ['newspaper', 'নিউজপেপার', null, 3],
        ['bangla', 'বাংলা', 'newspaper', 1],
            ['national', 'জাতীয়', 'bangla', 1],
            ['english', 'ইংরেজি', 'bangla', 2],
            ['local', 'লোকাল', 'bangla', 3],
            ['online', 'অনলাইন', 'bangla', 4],
            ['tv', 'টিভি চ্যানেল', 'bangla', 5],
            ['radio', 'রেডিও', 'bangla', 6],
            ['probashi', 'প্রবাসী', 'bangla', 7],
            ['tech', 'টেকনোলজি', 'bangla', 8],
            ['jobs', 'চাকরির খবর', 'bangla', 9],
            ['magazine', 'ম্যাগাজিন', 'bangla', 10],
        ['indian', 'ইন্ডিয়ান', 'newspaper', 2],
            ['indian_nat', 'জাতীয় (বাংলা)', 'indian', 1],
            ['indian_eng', 'ইংরেজি', 'indian', 2],
            ['indian_local', 'লোকাল (কলকাতা/ত্রিপুরা)', 'indian', 3],
        ['pakistan', 'পাকিস্তান', 'newspaper', 3],
            ['pak_eng', 'ইংরেজি (English)', 'pakistan', 1],
            ['pak_urdu', 'উর্দু (Urdu)', 'pakistan', 2],
        ['myanmar', 'মায়ানমার', 'newspaper', 4],
            ['my_national', 'জাতীয়', 'myanmar', 1],
            ['my_english', 'ইংরেজি', 'myanmar', 2],
            ['my_local', 'লোকাল', 'myanmar', 3],
            ['my_online', 'অনলাইন', 'myanmar', 4],
        ['international', 'ইন্টান্যাশনাল', 'newspaper', 5],
    ['facebook', 'ফেসবুক', null, 4],
        ['fb_national', 'জাতীয় সংবাদ (FB)', 'facebook', 1],
        ['fb_online', 'অনলাইন পোর্টাল (FB)', 'facebook', 2],
        ['fb_tv', 'টিভি চ্যানেল (FB)', 'facebook', 3],
        ['fb_radio', 'রেডিও (FB)', 'facebook', 4],
        ['fb_local', 'লোকাল সংবাদ (FB)', 'facebook', 5],
        ['fb_indian', 'ইন্ডিয়ান মিডিয়া (FB)', 'facebook', 6],
        ['fb_pakistan', 'পাকিস্তান মিডিয়া (FB)', 'facebook', 7],
        ['fb_international', 'ইন্টারন্যাশনাল (FB)', 'facebook', 8],
        ['fb_myanmar', 'মায়ানমার মিডিয়া (FB)', 'facebook', 9],
        ['fb_defense', 'প্রতিরক্ষা বাহিনী', 'facebook', 10],
        ['fb_police', 'আইন-শৃঙ্খলা', 'facebook', 11],
        ['fb_govt', 'সরকারি সংস্থা', 'facebook', 12],
        ['fb_pahari', 'পাহাড়ী সংগঠন', 'facebook', 13],
    ['youtube', 'ইউটিউব', null, 5],
        ['yt_news', 'সংবাদ', 'youtube', 1],
        ['yt_entertainment', 'বিনোদন', 'youtube', 2],
        ['yt_tech', 'প্রযুক্তি', 'youtube', 3],
        ['yt_islamic', 'ইসলামিক', 'youtube', 5],
        ['yt_defense', 'প্রতিরক্ষা', 'youtube', 9],
        ['yt_pahari', 'পাহাড়ী', 'youtube', 8],
        ['yt_influencer', 'ইনফ্লুয়েন্সার', 'youtube', 10],
    ['talkshow', 'টকশো', null, 6],
        ['latest_updates', 'লেটেস্ট আপডেট', 'talkshow', 1],
        ['ts_neutral', 'নিরপেক্ষ / মেইনস্ট্রিম', 'talkshow', 2],
        ['ts_awami', 'আওয়ামী পন্থী', 'talkshow', 3],
        ['ts_bnp', 'বিএনপি পন্থী', 'talkshow', 4],
        ['ts_jamaat', 'জামায়াত / ইসলামিক', 'talkshow', 5],
        ['ts_activist', 'অনলাইন অ্যাক্টিভিস্ট', 'talkshow', 6],
        ['ts_army', 'সেনা অফিসার', 'talkshow', 7],
    ['propagandist', 'প্রপাগান্ডিষ্ট', null, 7],
        ['prop_awami', 'আওয়ামী পন্থী', 'propagandist', 1],
        ['prop_bnp', 'বিএনপি পন্থী', 'propagandist', 2],
        ['prop_jamaat', 'জামায়াত পন্থী', 'propagandist', 3],
        ['prop_others', 'অন্যান্য', 'propagandist', 4],
    ['tools', 'টুলস', null, 8],
        ['open_tools', 'টুলস প্যানেল', 'tools', 1],
        ['trend_news', 'ট্রেন্ড নিউজ', 'tools', 3],
        ['phonebook', 'মোবাইল নং', 'tools', 4],
        ['fact_check', 'ফ্যাক্ট চেক', 'tools', 5],
];
?>
