
<?php
// api/data_news.php
return [
    // BD National
    ['np_01', 'প্রথম আলো', 'https://www.prothomalo.com', 'newspaper', 'bangla', 'national', 1],
    ['np_02', 'কালের কণ্ঠ', 'https://www.kalerkantho.com', 'newspaper', 'bangla', 'national', 2],
    ['np_03', 'যুগান্তর', 'https://www.jugantor.com', 'newspaper', 'bangla', 'national', 3],
    ['np_04', 'ইত্তেফাক', 'https://www.ittefaq.com.bd', 'newspaper', 'bangla', 'national', 4],
    ['np_05', 'সমকাল', 'https://samakal.com', 'newspaper', 'bangla', 'national', 5],
    ['np_06', 'নয়া দিগন্ত', 'https://www.dailynayadiganta.com', 'newspaper', 'bangla', 'national', 6],
    ['np_07', 'জনকণ্ঠ', 'https://www.dailyjanakantha.com', 'newspaper', 'bangla', 'national', 7],
    ['np_08', 'ইনকিলাব', 'https://www.dailyinqilab.com', 'newspaper', 'bangla', 'national', 8],
    ['np_09', 'মানবজমিন', 'https://mzamin.com', 'newspaper', 'bangla', 'national', 9],
    ['np_10', 'বাংলাদেশ প্রতিদিন', 'https://www.bd-pratidin.com', 'newspaper', 'bangla', 'national', 10],
    ['np_11', 'ভোরের কাগজ', 'https://www.bhorerkagoj.com', 'newspaper', 'bangla', 'national', 11],
    ['np_12', 'আমাদের সময়', 'https://www.dainikamadershomoy.com', 'newspaper', 'bangla', 'national', 12],
    ['np_13', 'যায়যায়দিন', 'https://www.jaijaidinbd.com', 'newspaper', 'bangla', 'national', 13],
    ['np_14', 'সংগ্রাম', 'https://dailysangram.com', 'newspaper', 'bangla', 'national', 14],
    ['np_15', 'সংবাদ', 'https://sangbad.net.bd', 'newspaper', 'bangla', 'national', 15],
    ['np_16', 'বণিক বার্তা', 'https://bonikbarta.net', 'newspaper', 'bangla', 'national', 16],
    ['np_17', 'কালবেলা', 'https://www.kalbela.com', 'newspaper', 'bangla', 'national', 17],
    ['np_18', 'দেশ রূপান্তর', 'https://www.deshrupantor.com', 'newspaper', 'bangla', 'national', 18],
    ['np_19', 'মানবকণ্ঠ', 'https://www.manobkantha.com.bd', 'newspaper', 'bangla', 'national', 19],
    ['np_20', 'আলোকিত বাংলাদেশ', 'https://www.alokitobangladesh.com', 'newspaper', 'bangla', 'national', 20],
    ['np_21', 'ভোরের পাতা', 'https://www.dailyvorerpata.com', 'newspaper', 'bangla', 'national', 21],
    ['np_22', 'খোলা কাগজ', 'https://www.kholakagojbd.com', 'newspaper', 'bangla', 'national', 22],
    ['np_23', 'আমাদের অর্থনীতি', 'https://www.amaderorthoneeti.com', 'newspaper', 'bangla', 'national', 23],
    ['np_24', 'শেয়ার বিজ', 'https://sharebiz.net', 'newspaper', 'bangla', 'national', 24],
    ['np_25', 'প্রতিদিনের সংবাদ', 'https://www.protidinersangbad.com', 'newspaper', 'bangla', 'national', 25],
    ['np_26', 'আজকের পত্রিকা', 'https://www.ajkerpatrika.com', 'newspaper', 'bangla', 'national', 26],
    ['np_27', 'সময়ের আলো', 'https://www.shomoyeralo.com', 'newspaper', 'bangla', 'national', 27],
    ['np_28', 'বাংলাদেশের খবর', 'https://www.bangladesherkhabor.net', 'newspaper', 'bangla', 'national', 28],
    ['np_29', 'আমার সংবাদ', 'https://www.amarsangbad.com', 'newspaper', 'bangla', 'national', 29],
    ['np_30', 'ঢাকা টাইমস', 'https://www.dhakatimes24.com', 'newspaper', 'bangla', 'national', 30],
    ['np_31', 'দৈনিক বাংলা', 'https://www.dainikbangla.com.bd', 'newspaper', 'bangla', 'national', 31],
    ['np_32', 'আজকের দর্পণ', 'https://www.ajkerdarpon.com', 'newspaper', 'bangla', 'national', 32],
    ['np_33', 'সরেজমিন বার্তা', 'https://www.sorejominbarta.com', 'newspaper', 'bangla', 'national', 33],
    ['np_34', 'নবাব', 'https://www.dailynabab.com', 'newspaper', 'bangla', 'national', 34],
    ['np_35', 'সংবাদ সারাবেলা', 'https://www.sangbadsarabela.com', 'newspaper', 'bangla', 'national', 35],
    ['np_36', 'বাংলাদেশ জার্নাল', 'https://www.bd-journal.com', 'newspaper', 'bangla', 'national', 36],
    ['np_37', 'অর্থনীতি প্রতিদিন', 'https://arthoniteeprotidin.com', 'newspaper', 'bangla', 'national', 37],
    ['np_38', 'খবরপত্র', 'https://www.khoborpatra.com', 'newspaper', 'bangla', 'national', 38],
    ['np_39', 'মানবজমিন (English)', 'https://mzamin.com/english', 'newspaper', 'bangla', 'english', 58],
    ['np_40', 'কালব', 'https://kalb.com.bd', 'newspaper', 'bangla', 'national', 40],

    // English Newspapers
    ['eng_01', 'The Daily Star', 'https://www.thedailystar.net', 'newspaper', 'bangla', 'english', 50],
    ['eng_02', 'Dhaka Tribune', 'https://www.dhakatribune.com', 'newspaper', 'bangla', 'english', 51],
    ['eng_03', 'New Age', 'https://www.newagebd.net', 'newspaper', 'bangla', 'english', 52],
    ['eng_04', 'The Independent', 'https://theindependentbd.com', 'newspaper', 'bangla', 'english', 53],
    ['eng_05', 'Daily Sun', 'https://www.daily-sun.com', 'newspaper', 'bangla', 'english', 54],
    ['eng_06', 'The Financial Express', 'https://thefinancialexpress.com.bd', 'newspaper', 'bangla', 'english', 55],
    ['eng_07', 'The Business Standard', 'https://www.tbsnews.net', 'newspaper', 'bangla', 'english', 56],
    ['eng_08', 'Daily Observer', 'https://www.observerbd.com', 'newspaper', 'bangla', 'english', 57],
    ['eng_09', 'The Bangladesh Today', 'https://thebangladeshtoday.com', 'newspaper', 'bangla', 'english', 59],
    ['eng_10', 'Asian Age', 'https://dailyasianage.com', 'newspaper', 'bangla', 'english', 60],
    ['eng_11', 'News Today', 'https://newstoday.com.bd', 'newspaper', 'bangla', 'english', 61],
    ['eng_12', 'Weekly Holiday', 'https://weeklyholiday.net', 'newspaper', 'bangla', 'english', 62],

    // Online Portals
    ['on_01', 'bdnews24', 'https://bangla.bdnews24.com', 'newspaper', 'bangla', 'online', 80],
    ['on_02', 'banglanews24', 'https://www.banglanews24.com', 'newspaper', 'bangla', 'online', 81],
    ['on_03', 'Jagonews24', 'https://www.jagonews24.com', 'newspaper', 'bangla', 'online', 82],
    ['on_04', 'Dhaka Post', 'https://www.dhakapost.com', 'newspaper', 'bangla', 'online', 83],
    ['on_05', 'Rising BD', 'https://www.risingbd.com', 'newspaper', 'bangla', 'online', 84],
    ['on_06', 'Barta24', 'https://barta24.com', 'newspaper', 'bangla', 'online', 85],
    ['on_07', 'Sarabangla', 'https://sarabangla.net', 'newspaper', 'bangla', 'online', 86],
    ['on_08', 'Bangla Tribune', 'https://www.banglatribune.com', 'newspaper', 'bangla', 'online', 87],
    ['on_09', 'The Report24', 'https://www.thereport24.com', 'newspaper', 'bangla', 'online', 88],
    ['on_10', 'Priyo.com', 'https://www.priyo.com', 'newspaper', 'bangla', 'online', 89],
    ['on_11', 'DMP News', 'https://dmpnews.org', 'newspaper', 'bangla', 'online', 90],
    ['on_12', 'Poriborton', 'https://poriborton.com', 'newspaper', 'bangla', 'online', 91],
    ['on_13', 'BdCricTime', 'https://www.bdcrictime.com', 'newspaper', 'bangla', 'online', 92],
    ['on_14', 'Tech Shohor', 'https://techshohor.com', 'newspaper', 'bangla', 'online', 93],
    ['on_15', 'Zoom Bangla', 'https://zoombangla.com', 'newspaper', 'bangla', 'online', 94],
    ['on_17', 'Anyadin', 'https://anyadin.com', 'newspaper', 'bangla', 'online', 96],
    ['on_18', 'Natun Barta', 'https://natunbarta.com', 'newspaper', 'bangla', 'online', 97],
    ['on_19', ' শীর্ষ সংবাদ', 'https://sheershasangbad.com', 'newspaper', 'bangla', 'online', 98],
    ['on_20', 'Breaking News BD', 'https://breakingnews.com.bd', 'newspaper', 'bangla', 'online', 99],

    // TV Channels
    ['tv_01', 'Somoy TV', 'https://www.somoynews.tv', 'newspaper', 'bangla', 'tv', 100],
    ['tv_02', 'Jamuna TV', 'https://www.jamuna.tv', 'newspaper', 'bangla', 'tv', 101],
    ['tv_03', 'Ekattor TV', 'https://ekattor.tv', 'newspaper', 'bangla', 'tv', 102],
    ['tv_04', 'Independent TV', 'https://www.independent24.com', 'newspaper', 'bangla', 'tv', 103],
    ['tv_05', 'Channel i', 'https://www.channelionline.com', 'newspaper', 'bangla', 'tv', 104],
    ['tv_06', 'NTV Online', 'https://www.ntvbd.com', 'newspaper', 'bangla', 'tv', 105],
    ['tv_07', 'RTV Online', 'https://www.rtvonline.com', 'newspaper', 'bangla', 'tv', 106],
    ['tv_08', 'ATN News', 'https://www.atnnewstv.com', 'newspaper', 'bangla', 'tv', 107],
    ['tv_09', 'Channel 24', 'https://www.channel24bd.tv', 'newspaper', 'bangla', 'tv', 108],
    ['tv_10', 'DBC News', 'https://dbcnews.tv', 'newspaper', 'bangla', 'tv', 109],
    ['tv_11', 'News24', 'https://www.news24bd.tv', 'newspaper', 'bangla', 'tv', 110],
    ['tv_12', 'Maasranga TV', 'https://maasranga.tv', 'newspaper', 'bangla', 'tv', 111],
    ['tv_13', 'Boishakhi TV', 'https://www.boishakhionline.com', 'newspaper', 'bangla', 'tv', 112],
    ['tv_14', 'Banglavision', 'https://bvnews24.com', 'newspaper', 'bangla', 'tv', 113],
    ['tv_15', 'Desh TV', 'https://desh.tv', 'newspaper', 'bangla', 'tv', 114],
    ['tv_16', 'GTV (Gazi)', 'https://gaazi.tv', 'newspaper', 'bangla', 'tv', 115],
    ['tv_17', 'SA TV', 'https://satv.tv', 'newspaper', 'bangla', 'tv', 116],
    ['tv_18', 'Mohona TV', 'https://mohona.tv', 'newspaper', 'bangla', 'tv', 117],
    ['tv_19', 'Asian TV', 'https://asiantvbd.tv', 'newspaper', 'bangla', 'tv', 118],
    ['tv_20', 'Bijoy TV', 'https://bijoy.tv', 'newspaper', 'bangla', 'tv', 119],
    ['tv_21', 'Dipto TV', 'https://www.dipto.tv', 'newspaper', 'bangla', 'tv', 120],
    ['tv_22', 'Nagorik TV', 'https://nagorik.com', 'newspaper', 'bangla', 'tv', 121],
    ['tv_23', 'Ekhon TV', 'https://ekhon.tv', 'newspaper', 'bangla', 'tv', 122],
    ['tv_24', 'Global TV', 'https://globaltvbd.com', 'newspaper', 'bangla', 'tv', 123],
    ['tv_25', 'Nexus TV', 'https://nexustelevision.com', 'newspaper', 'bangla', 'tv', 124],
    ['tv_26', 'My TV', 'https://mytvbd.tv', 'newspaper', 'bangla', 'tv', 125],

    // Radio
    ['rad_01', 'Radio Today', 'https://radiotodaybd.fm', 'newspaper', 'bangla', 'radio', 130],
    ['rad_02', 'Radio Foorti', 'https://radiofoorti.fm', 'newspaper', 'bangla', 'radio', 131],
    ['rad_03', 'Dhaka FM', 'https://dhakafm904.com', 'newspaper', 'bangla', 'radio', 132],
    ['rad_04', 'ABC Radio', 'https://abcradio.fm', 'newspaper', 'bangla', 'radio', 133],
    ['rad_05', 'Jago FM', 'https://jago.fm', 'newspaper', 'bangla', 'radio', 134],
    ['rad_06', 'Radio Bhumi', 'https://radiobhumi.fm', 'newspaper', 'bangla', 'radio', 135],
    ['rad_07', 'Bangladesh Betar', 'http://www.betar.gov.bd', 'newspaper', 'bangla', 'radio', 136],
    ['rad_08', 'Peoples Radio', 'https://peoplesradio.fm', 'newspaper', 'bangla', 'radio', 137],
    ['rad_09', 'Radio Next', 'https://radionext.fm', 'newspaper', 'bangla', 'radio', 138],
    ['rad_10', 'Spice FM', 'https://spicefm.bd', 'newspaper', 'bangla', 'radio', 139],

    // Local
    ['loc_ctg_01', 'Dainik Azadi', 'https://dainikazadi.net', 'newspaper', 'bangla', 'local', 150],
    ['loc_ctg_02', 'Dainik Purbokone', 'https://dainikpurbokone.net', 'newspaper', 'bangla', 'local', 151],
    ['loc_ctg_03', 'Suprobhat Bangladesh', 'https://suprobhat.com', 'newspaper', 'bangla', 'local', 152],
    ['loc_ctg_04', 'Coxsbazar News (CBN)', 'https://cbn24.com', 'newspaper', 'bangla', 'local', 153],
    ['loc_syl_01', 'Sylhet View', 'https://www.sylhetview24.com', 'newspaper', 'bangla', 'local', 154],
    ['loc_syl_02', 'Dainik Sylhet', 'https://dainiksylhet.com', 'newspaper', 'bangla', 'local', 155],
    ['loc_khl_01', 'Dainik Purbanchal', 'https://purbanchal.com', 'newspaper', 'bangla', 'local', 156],
    ['loc_khl_02', 'Gramer Kagoj (Jashore)', 'https://gramerkagoj.com', 'newspaper', 'bangla', 'local', 157],
    ['loc_khl_03', 'Mathabhanga (Chuadanga)', 'https://mathabhanga.com', 'newspaper', 'bangla', 'local', 158],
    ['loc_raj_01', 'Sonali Sangbad', 'https://sonalisangbad.com', 'newspaper', 'bangla', 'local', 159],
    ['loc_raj_02', 'Karatoa (Bogra)', 'https://www.karatoa.com.bd', 'newspaper', 'bangla', 'local', 160],
    ['loc_bar_01', 'Barisal Times', 'https://www.barisaltimes.com', 'newspaper', 'bangla', 'local', 161],
    ['loc_rng_01', 'Dainik Karatoa', 'https://karatoa.com.bd', 'newspaper', 'bangla', 'local', 162],
    ['loc_rng_02', 'Uttor Bangla', 'https://uttorbangla.com', 'newspaper', 'bangla', 'local', 163],
    ['loc_cht_01', 'Paharchura', 'https://paharchura.com', 'newspaper', 'bangla', 'local', 164],
    ['loc_cht_02', 'CHT News', 'https://chtnews.blogspot.com', 'newspaper', 'bangla', 'local', 165],

    // Indian
    ['ind_bn_01', 'Anandabazar Patrika', 'https://www.anandabazar.com', 'newspaper', 'indian', 'indian_nat', 200],
    ['ind_bn_02', 'Bartaman', 'https://bartamanpatrika.com', 'newspaper', 'indian', 'indian_nat', 201],
    ['ind_bn_03', 'Sangbad Pratidin', 'https://www.sangbadpratidin.in', 'newspaper', 'indian', 'indian_nat', 202],
    ['ind_bn_04', 'Aajkaal', 'https://www.aajkaal.in', 'newspaper', 'indian', 'indian_nat', 203],
    ['ind_bn_05', 'Ei Samay', 'https://eisamay.com', 'newspaper', 'indian', 'indian_nat', 204],
    ['ind_bn_06', 'Ganashakti', 'https://ganashakti.com', 'newspaper', 'indian', 'indian_nat', 205],
    ['ind_bn_07', 'Puber Kalom', 'https://puberkalom.com', 'newspaper', 'indian', 'indian_nat', 206],
    ['ind_bn_08', 'Uttarbanga Sambad', 'https://uttarbangasambad.com', 'newspaper', 'indian', 'indian_local', 207],
    ['ind_bn_09', 'Syandan Patrika (Tripura)', 'https://syandanpatrika.com', 'newspaper', 'indian', 'indian_local', 208],
    ['ind_bn_10', 'Dainik Sambad (Tripura)', 'https://dainiksambad.com', 'newspaper', 'indian', 'indian_local', 209],
    ['ind_en_01', 'The Hindu', 'https://www.thehindu.com', 'newspaper', 'indian', 'indian_eng', 210],
    ['ind_en_02', 'Times of India', 'https://timesofindia.indiatimes.com', 'newspaper', 'indian', 'indian_eng', 211],
    ['ind_en_03', 'Hindustan Times', 'https://www.hindustantimes.com', 'newspaper', 'indian', 'indian_eng', 212],
    ['ind_en_04', 'NDTV', 'https://www.ndtv.com', 'newspaper', 'indian', 'indian_eng', 213],
    ['ind_en_05', 'Indian Express', 'https://indianexpress.com', 'newspaper', 'indian', 'indian_eng', 214],

    // Pakistan
    ['pak_en_01', 'Dawn', 'https://www.dawn.com', 'newspaper', 'pakistan', 'pak_eng', 250],
    ['pak_en_02', 'The News International', 'https://www.thenews.com.pk', 'newspaper', 'pakistan', 'pak_eng', 251],
    ['pak_en_03', 'The Express Tribune', 'https://tribune.com.pk', 'newspaper', 'pakistan', 'pak_eng', 252],
    ['pak_en_04', 'The Nation', 'https://nation.com.pk', 'newspaper', 'pakistan', 'pak_eng', 253],
    ['pak_en_05', 'Daily Times', 'https://dailytimes.com.pk', 'newspaper', 'pakistan', 'pak_eng', 254],
    ['pak_ur_01', 'Daily Jang', 'https://jang.com.pk', 'newspaper', 'pakistan', 'pak_urdu', 260],
    ['pak_ur_02', 'Daily Express', 'https://www.express.com.pk', 'newspaper', 'pakistan', 'pak_urdu', 261],
    ['pak_ur_03', 'Nawaiwaqt', 'https://www.nawaiwaqt.com.pk', 'newspaper', 'pakistan', 'pak_urdu', 262],
    ['pak_ur_04', 'Dunya News', 'https://dunya.com.pk', 'newspaper', 'pakistan', 'pak_urdu', 263],

    // Myanmar
    ['myn_01', 'The Irrawaddy', 'https://www.irrawaddy.com', 'newspaper', 'myanmar', 'my_english', 300],
    ['myn_02', 'Myanmar Now', 'https://myanmar-now.org', 'newspaper', 'myanmar', 'my_english', 301],
    ['myn_03', 'Mizzima', 'https://www.mizzima.com', 'newspaper', 'myanmar', 'my_english', 302],
    ['myn_04', 'Khit Thit Media', 'https://www.khitthitmedia.org', 'newspaper', 'myanmar', 'my_online', 303],
    ['myn_05', 'Narinjara News', 'https://narinjara.com', 'newspaper', 'myanmar', 'my_local', 304],
    ['myn_06', 'DVB (Democratic Voice of Burma)', 'https://english.dvb.no', 'newspaper', 'myanmar', 'my_online', 305],
    ['myn_07', 'Global New Light of Myanmar', 'https://www.gnlm.com.mm', 'newspaper', 'myanmar', 'my_national', 306],
    ['myn_08', 'Eleven Myanmar', 'https://elevenmyanmar.com', 'newspaper', 'myanmar', 'my_english', 307],
    ['myn_09', 'The Voice', 'https://voice-daily.com', 'newspaper', 'myanmar', 'my_local', 308],
    ['myn_10', 'Karen News', 'https://karennews.org', 'newspaper', 'myanmar', 'my_local', 309],
    ['myn_11', 'Shan News', 'https://english.shannews.org', 'newspaper', 'myanmar', 'my_local', 310],

    // International
    ['int_01', 'BBC News', 'https://www.bbc.com', 'newspaper', 'international', '', 400],
    ['int_02', 'BBC Bangla', 'https://www.bbc.com/bengali', 'newspaper', 'international', '', 401],
    ['int_03', 'CNN', 'https://edition.cnn.com', 'newspaper', 'international', '', 402],
    ['int_04', 'Al Jazeera', 'https://www.aljazeera.com', 'newspaper', 'international', '', 403],
    ['int_05', 'Reuters', 'https://www.reuters.com', 'newspaper', 'international', '', 404],
    ['int_06', 'The Guardian', 'https://www.theguardian.com', 'newspaper', 'international', '', 405],
    ['int_07', 'New York Times', 'https://www.nytimes.com', 'newspaper', 'international', '', 406],
    ['int_08', 'DW (Deutsche Welle)', 'https://www.dw.com', 'newspaper', 'international', '', 407],
    ['int_09', 'VOA Bangla', 'https://www.voabangla.com', 'newspaper', 'international', '', 408],
    ['int_10', 'AFP', 'https://www.afp.com', 'newspaper', 'international', '', 409],
    ['int_11', 'Bloomberg', 'https://www.bloomberg.com', 'newspaper', 'international', '', 410],
    ['int_12', 'Wall Street Journal', 'https://www.wsj.com', 'newspaper', 'international', '', 411],
    ['int_13', 'Washington Post', 'https://www.washingtonpost.com', 'newspaper', 'international', '', 412],
    ['int_14', 'France 24', 'https://www.france24.com', 'newspaper', 'international', '', 413],
    ['int_15', 'RT (Russia Today)', 'https://www.rt.com', 'newspaper', 'international', '', 414],
    ['int_16', 'Xinhua', 'http://www.xinhuanet.com/english', 'newspaper', 'international', '', 415],
    ['int_17', 'TRT World', 'https://www.trtworld.com', 'newspaper', 'international', '', 416],
    ['int_18', 'CNA (Singapore)', 'https://www.channelnewsasia.com', 'newspaper', 'international', '', 417],
    ['int_19', 'NHK World', 'https://www3.nhk.or.jp/nhkworld', 'newspaper', 'international', '', 418],
    ['int_20', 'South China Morning Post', 'https://www.scmp.com', 'newspaper', 'international', '', 419]
];
?>
