
<?php
// api/data_social.php
return [
    // Facebook Links
    ['fb_np_01', 'Prothom Alo FB', 'https://www.facebook.com/DailyProthomAlo', 'facebook', 'fb_national', '', 1500],
    ['fb_np_02', 'Kaler Kantho FB', 'https://www.facebook.com/kalerkantho', 'facebook', 'fb_national', '', 1501],
    ['fb_np_03', 'Jugantor FB', 'https://www.facebook.com/dainikjugantor', 'facebook', 'fb_national', '', 1502],
    ['fb_np_04', 'Ittefaq FB', 'https://www.facebook.com/dailyittefaq', 'facebook', 'fb_national', '', 1503],
    ['fb_np_05', 'Samakal FB', 'https://www.facebook.com/samakal', 'facebook', 'fb_national', '', 1504],
    ['fb_np_06', 'Naya Diganta FB', 'https://www.facebook.com/dailynayadiganta', 'facebook', 'fb_national', '', 1505],
    ['fb_np_07', 'Janakantha FB', 'https://www.facebook.com/dailyjanakantha', 'facebook', 'fb_national', '', 1506],
    ['fb_np_08', 'Inqilab FB', 'https://www.facebook.com/DailyInqilabOnline', 'facebook', 'fb_national', '', 1507],
    ['fb_np_09', 'Manabzamin FB', 'https://www.facebook.com/dailymanabzamin', 'facebook', 'fb_national', '', 1508],
    ['fb_np_10', 'Bangladesh Pratidin FB', 'https://www.facebook.com/bdpratidin', 'facebook', 'fb_national', '', 1509],
    ['fb_np_11', 'Bhorer Kagoj FB', 'https://www.facebook.com/BhorerKagoj.Live', 'facebook', 'fb_national', '', 1510],
    ['fb_np_12', 'Amader Shomoy FB', 'https://www.facebook.com/dainikamadershomoy', 'facebook', 'fb_national', '', 1511],
    ['fb_np_13', 'Jaijaidin FB', 'https://www.facebook.com/jaijaidinbd', 'facebook', 'fb_national', '', 1512],
    ['fb_np_14', 'Bonik Barta FB', 'https://www.facebook.com/dailybonikbarta', 'facebook', 'fb_national', '', 1513],
    ['fb_np_15', 'Kalbela FB', 'https://www.facebook.com/kalbelaonline', 'facebook', 'fb_national', '', 1514],
    ['fb_np_16', 'Desh Rupantor FB', 'https://www.facebook.com/deshrupantor', 'facebook', 'fb_national', '', 1515],
    ['fb_np_17', 'Daily Star FB', 'https://www.facebook.com/dailystarnews', 'facebook', 'fb_national', '', 1516],
    ['fb_np_18', 'Dhaka Tribune FB', 'https://www.facebook.com/DhakaTribune', 'facebook', 'fb_national', '', 1517],
    ['fb_np_19', 'Business Standard FB', 'https://www.facebook.com/tbsnews.net', 'facebook', 'fb_national', '', 1518],
    ['fb_on_01', 'bdnews24 FB', 'https://www.facebook.com/bdnews24', 'facebook', 'fb_online', '', 1550],
    ['fb_on_02', 'banglanews24 FB', 'https://www.facebook.com/banglanews24', 'facebook', 'fb_online', '', 1551],
    ['fb_on_03', 'Jagonews24 FB', 'https://www.facebook.com/jagonews24', 'facebook', 'fb_online', '', 1552],
    ['fb_on_04', 'Dhaka Post FB', 'https://www.facebook.com/DPostOnline', 'facebook', 'fb_online', '', 1553],
    ['fb_on_05', 'Rising BD FB', 'https://www.facebook.com/Dailyrisingbd', 'facebook', 'fb_online', '', 1554],
    ['fb_on_06', 'Barta24 FB', 'https://www.facebook.com/Barta24BD', 'facebook', 'fb_online', '', 1555],
    ['fb_on_07', 'Sarabangla FB', 'https://www.facebook.com/sarabangla.net', 'facebook', 'fb_online', '', 1556],
    ['fb_on_08', 'Bangla Tribune FB', 'https://www.facebook.com/BanglaTribuneOnline', 'facebook', 'fb_online', '', 1557],
    ['fb_tv_01', 'Somoy TV FB', 'https://www.facebook.com/somoynews.tv', 'facebook', 'fb_tv', '', 1600],
    ['fb_tv_02', 'Jamuna TV FB', 'https://www.facebook.com/JamunaTelevision', 'facebook', 'fb_tv', '', 1601],
    ['fb_tv_03', 'Ekattor TV FB', 'https://www.facebook.com/ekattor.tv', 'facebook', 'fb_tv', '', 1602],
    ['fb_tv_04', 'Independent TV FB', 'https://www.facebook.com/IndependentTVNews', 'facebook', 'fb_tv', '', 1603],
    ['fb_tv_05', 'Channel i FB', 'https://www.facebook.com/channelionline', 'facebook', 'fb_tv', '', 1604],
    ['fb_tv_06', 'NTV FB', 'https://www.facebook.com/ntvdigital', 'facebook', 'fb_tv', '', 1605],
    ['fb_tv_07', 'RTV FB', 'https://www.facebook.com/rtvonline', 'facebook', 'fb_tv', '', 1606],
    ['fb_tv_08', 'ATN News FB', 'https://www.facebook.com/atnnewstv', 'facebook', 'fb_tv', '', 1607],
    ['fb_tv_09', 'Channel 24 FB', 'https://www.facebook.com/channel24bd.tv', 'facebook', 'fb_tv', '', 1608],
    ['fb_tv_10', 'DBC News FB', 'https://www.facebook.com/dbcnews.tv', 'facebook', 'fb_tv', '', 1609],
    ['fb_tv_11', 'News24 FB', 'https://www.facebook.com/news24bd.tv', 'facebook', 'fb_tv', '', 1610],
    ['fb_tv_12', 'Maasranga FB', 'https://www.facebook.com/MaasrangaTelevision', 'facebook', 'fb_tv', '', 1611],
    ['fb_tv_13', 'GTV FB', 'https://www.facebook.com/GaziSatelliteTelevisionLtd', 'facebook', 'fb_tv', '', 1612],
    ['fb_tv_14', 'Desh TV FB', 'https://www.facebook.com/deshtv', 'facebook', 'fb_tv', '', 1613],
    ['fb_tv_15', 'Boishakhi TV FB', 'https://www.facebook.com/boishakhimedia', 'facebook', 'fb_tv', '', 1614],
    ['fb_rad_01', 'Radio Today FB', 'https://www.facebook.com/RadioTodayFM89.6', 'facebook', 'fb_radio', '', 1650],
    ['fb_rad_02', 'Radio Foorti FB', 'https://www.facebook.com/radiofoorti', 'facebook', 'fb_radio', '', 1651],
    ['fb_rad_03', 'Dhaka FM FB', 'https://www.facebook.com/dhakafm90.4', 'facebook', 'fb_radio', '', 1652],
    ['fb_rad_04', 'ABC Radio FB', 'https://www.facebook.com/abcradiofm89.2', 'facebook', 'fb_radio', '', 1653],
    ['fb_rad_05', 'Jago FM FB', 'https://www.facebook.com/jago.fm', 'facebook', 'fb_radio', '', 1654],
    ['fb_rad_06', 'Bangladesh Betar FB', 'https://www.facebook.com/BangladeshBetar.Gov.Bd', 'facebook', 'fb_radio', '', 1655],
    ['fb_rad_07', 'BBC Bangla Radio FB', 'https://www.facebook.com/BBCnewsBangla', 'facebook', 'fb_radio', '', 1656],
    ['fb_loc_01', 'Dainik Azadi FB (CTG)', 'https://www.facebook.com/dainikazadi', 'facebook', 'fb_local', '', 1700],
    ['fb_loc_02', 'Dainik Purbokone FB', 'https://www.facebook.com/dainikpurbokone', 'facebook', 'fb_local', '', 1701],
    ['fb_loc_03', 'Sylhet View FB', 'https://www.facebook.com/sylhetview24', 'facebook', 'fb_local', '', 1702],
    ['fb_loc_04', 'Gramer Kagoj FB (Jashore)', 'https://www.facebook.com/gramerkagoj', 'facebook', 'fb_local', '', 1703],
    ['fb_loc_05', 'Coxsbazar News FB', 'https://www.facebook.com/cbn24', 'facebook', 'fb_local', '', 1704],
    ['fb_loc_06', 'Purbanchal FB (Khulna)', 'https://www.facebook.com/daily-purbanchal', 'facebook', 'fb_local', '', 1705],
    ['fb_ind_01', 'Anandabazar FB', 'https://www.facebook.com/anandabazar.abp', 'facebook', 'fb_indian', '', 1750],
    ['fb_ind_02', '24 Ghanta FB', 'https://www.facebook.com/zeenews', 'facebook', 'fb_indian', '', 1751],
    ['fb_ind_03', 'ABP Ananda FB', 'https://www.facebook.com/abpananda', 'facebook', 'fb_indian', '', 1752],
    ['fb_ind_04', 'The Hindu FB', 'https://www.facebook.com/thehindu', 'facebook', 'fb_indian', '', 1753],
    ['fb_ind_05', 'Times of India FB', 'https://www.facebook.com/TimesofIndia', 'facebook', 'fb_indian', '', 1754],
    ['fb_ind_06', 'NDTV FB', 'https://www.facebook.com/ndtv', 'facebook', 'fb_indian', '', 1755],
    ['fb_ind_07', 'Republic Bangla FB', 'https://www.facebook.com/RepublicBangla', 'facebook', 'fb_indian', '', 1756],
    ['fb_pak_01', 'Dawn News FB', 'https://www.facebook.com/dawn.com', 'facebook', 'fb_pakistan', '', 1780],
    ['fb_pak_02', 'Geo News FB', 'https://www.facebook.com/GeoNews', 'facebook', 'fb_pakistan', '', 1781],
    ['fb_pak_03', 'ARY News FB', 'https://www.facebook.com/arynewsasia', 'facebook', 'fb_pakistan', '', 1782],
    ['fb_pak_04', 'Samaa TV FB', 'https://www.facebook.com/samaatvnews', 'facebook', 'fb_pakistan', '', 1783],
    ['fb_int_01', 'BBC News FB', 'https://www.facebook.com/bbcnews', 'facebook', 'fb_international', '', 1800],
    ['fb_int_02', 'CNN FB', 'https://www.facebook.com/cnn', 'facebook', 'fb_international', '', 1801],
    ['fb_int_03', 'Al Jazeera FB', 'https://www.facebook.com/aljazeera', 'facebook', 'fb_international', '', 1802],
    ['fb_int_04', 'Reuters FB', 'https://www.facebook.com/Reuters', 'facebook', 'fb_international', '', 1803],
    ['fb_int_05', 'DW Bangla FB', 'https://www.facebook.com/dw.bengali', 'facebook', 'fb_international', '', 1804],
    ['fb_myn_01', 'The Irrawaddy FB', 'https://www.facebook.com/theirrawaddy', 'facebook', 'fb_myanmar', '', 1850],
    ['fb_myn_02', 'Myanmar Now FB', 'https://www.facebook.com/myanmarnownews', 'facebook', 'fb_myanmar', '', 1851],
    ['fb_myn_03', 'Mizzima FB', 'https://www.facebook.com/MizzimaDaily', 'facebook', 'fb_myanmar', '', 1852],
    ['fb_myn_04', 'Khit Thit Media FB', 'https://www.facebook.com/khitthitnews', 'facebook', 'fb_myanmar', '', 1853],
    ['fb_myn_05', 'Eleven Media FB', 'https://www.facebook.com/ElevenMediaGroup', 'facebook', 'fb_myanmar', '', 1854],
    ['fb_myn_06', 'DVB FB', 'https://www.facebook.com/DVBTVNews', 'facebook', 'fb_myanmar', '', 1855],
    ['fb_def_01', 'Bangladesh Army', 'https://www.facebook.com/bdarmy.army.mil.bd', 'facebook', 'fb_defense', '', 500],
    ['fb_def_02', 'Bangladesh Navy', 'https://www.facebook.com/BangladeshNavyOfficial', 'facebook', 'fb_defense', '', 501],
    ['fb_def_03', 'Bangladesh Air Force', 'https://www.facebook.com/baf.mil.bd', 'facebook', 'fb_defense', '', 502],
    ['fb_def_04', 'ISPR', 'https://www.facebook.com/ISPR.Bangladesh', 'facebook', 'fb_defense', '', 503],
    ['fb_def_05', 'Border Guard Bangladesh', 'https://www.facebook.com/bgb.gov.bd', 'facebook', 'fb_defense', '', 504],
    ['fb_pol_01', 'Bangladesh Police', 'https://www.facebook.com/BangladeshPoliceOfficialPage', 'facebook', 'fb_police', '', 510],
    ['fb_pol_02', 'RAB', 'https://www.facebook.com/rabonlinemediacell', 'facebook', 'fb_police', '', 511],
    ['fb_pol_03', 'DMP', 'https://www.facebook.com/dmpdhaka', 'facebook', 'fb_police', '', 512],
    ['fb_pol_04', 'Fire Service', 'https://www.facebook.com/fscd.bd', 'facebook', 'fb_police', '', 513],
    ['fb_gov_01', 'ICT Division', 'https://www.facebook.com/ictdivisionbd', 'facebook', 'fb_govt', '', 520],
    ['fb_gov_02', 'Bangladesh Govt', 'https://www.facebook.com/BangladeshGov', 'facebook', 'fb_govt', '', 521],
    ['fb_pah_01', 'Arakan Army (The Way of Rakhita)', 'https://www.facebook.com/TheWayOfRakhita', 'facebook', 'fb_pahari', '', 530],
    ['fb_pah_02', 'UPDF', 'https://www.facebook.com/updf.org', 'facebook', 'fb_pahari', '', 531],
    ['fb_pah_03', 'PCJSS', 'https://www.facebook.com/pcjss.org', 'facebook', 'fb_pahari', '', 532],
    ['fb_pah_04', 'Basherkella', 'https://www.facebook.com/Basherkella.Official', 'facebook', 'fb_online', '', 533],

    // YouTube Links
    ['yt_news_01', 'Somoy TV', 'https://www.youtube.com/@somoynews360', 'youtube', 'yt_news', '', 600],
    ['yt_news_02', 'Jamuna TV', 'https://www.youtube.com/@JamunaTVbd', 'youtube', 'yt_news', '', 601],
    ['yt_news_03', 'Ekattor TV', 'https://www.youtube.com/@ekattor_tv', 'youtube', 'yt_news', '', 602],
    ['yt_news_04', 'Independent TV', 'https://www.youtube.com/@IndependentTelevision', 'youtube', 'yt_news', '', 603],
    ['yt_news_05', 'Channel i News', 'https://www.youtube.com/@ChanneliNews', 'youtube', 'yt_news', '', 604],
    ['yt_news_06', 'ATN News', 'https://www.youtube.com/@atnnewslive', 'youtube', 'yt_news', '', 605],
    ['yt_news_07', 'DBC News', 'https://www.youtube.com/@dbcnews_tv', 'youtube', 'yt_news', '', 606],
    ['yt_news_08', 'News24', 'https://www.youtube.com/@News24tvchannel', 'youtube', 'yt_news', '', 607],
    ['yt_news_09', 'Maasranga TV', 'https://www.youtube.com/@MaasrangaTelevisionNews', 'youtube', 'yt_news', '', 608],
    ['yt_news_10', 'Desh TV', 'https://www.youtube.com/@DeshTVNews', 'youtube', 'yt_news', '', 609],
    ['yt_news_11', 'Channel 24', 'https://www.youtube.com/@Channel24Youtube', 'youtube', 'yt_news', '', 610],
    ['yt_news_12', 'RTV News', 'https://www.youtube.com/@RtvNews', 'youtube', 'yt_news', '', 611],
    ['yt_news_13', 'NTV News', 'https://www.youtube.com/@ntvnewsbd', 'youtube', 'yt_news', '', 612],
    ['yt_ind_01', 'ABP Ananda', 'https://www.youtube.com/@ABPAnanda', 'youtube', 'yt_news', '', 615],
    ['yt_ind_02', 'Zee 24 Ghanta', 'https://www.youtube.com/@Zee24Ghanta', 'youtube', 'yt_news', '', 616],
    ['yt_ind_03', 'Republic Bangla', 'https://www.youtube.com/@RepublicBangla', 'youtube', 'yt_news', '', 617],
    ['yt_ind_04', 'NDTV', 'https://www.youtube.com/@NDTV', 'youtube', 'yt_news', '', 618],
    ['yt_int_01', 'BBC News', 'https://www.youtube.com/@BBCNews', 'youtube', 'yt_news', '', 619],
    ['yt_int_02', 'Al Jazeera', 'https://www.youtube.com/@aljazeera', 'youtube', 'yt_news', '', 620],
    ['yt_int_03', 'DW News', 'https://www.youtube.com/@dwnews', 'youtube', 'yt_news', '', 621],
    ['yt_def_01', 'Bangladesh Army', 'https://www.youtube.com/@BangladeshArmy_official', 'youtube', 'yt_defense', '', 630],
    ['yt_def_02', 'Bangladesh Navy', 'https://www.youtube.com/@BangladeshNavy', 'youtube', 'yt_defense', '', 631],
    ['yt_def_03', 'Bangladesh Air Force', 'https://www.youtube.com/@BangladeshAirForce', 'youtube', 'yt_defense', '', 632],
    ['yt_def_04', 'Border Guard Bangladesh', 'https://www.youtube.com/@BorderGuardBangladesh', 'youtube', 'yt_defense', '', 633],
    ['yt_pah_01', 'Arakan Army Media', 'https://www.youtube.com/@ArakanArmyMedia', 'youtube', 'yt_pahari', '', 640],
    ['yt_pah_02', 'UPDF Media', 'https://www.youtube.com/@UPDFMedia', 'youtube', 'yt_pahari', '', 641],

    // Talkshows
    ['ts_neu_01', 'Tritiyo Matra', 'https://www.youtube.com/@TritiyoMatra', 'talkshow', 'ts_neutral', '', 900],
    ['ts_neu_02', 'Channel i Talkshow', 'https://www.youtube.com/@ChanneliNews', 'talkshow', 'ts_neutral', '', 901],
    ['ts_neu_03', 'ATN News Talkshow', 'https://www.youtube.com/@atnnewslive', 'talkshow', 'ts_neutral', '', 902],
    ['ts_al_01', 'Ekattor TV Talkshow', 'https://www.youtube.com/@ekattor_tv', 'talkshow', 'ts_awami', '', 920],
    ['ts_bnp_01', 'BNP Media Cell', 'https://www.youtube.com/@bnpmediacell', 'talkshow', 'ts_bnp', '', 940],
    ['ts_act_02', 'Pinaki Bhattacharya', 'https://www.youtube.com/@PinakiBhattacharya', 'talkshow', 'ts_activist', '', 981],
    ['ts_act_03', 'Elias Hossain', 'https://www.youtube.com/@EliasHossain', 'talkshow', 'ts_activist', '', 982],
    ['ts_act_04', 'Konak Sarwar', 'https://www.youtube.com/@KonakSarwar', 'talkshow', 'ts_activist', '', 983],
    ['ts_act_06', 'Netra News', 'https://www.youtube.com/@NetraNews', 'talkshow', 'ts_activist', '', 985],
];
?>
