
<?php
// api/seed_data.php

return [
    // --- 1. MENUS ---
    'menus' => [
        ['monitor', 'কিওয়ার্ড মনিটর', null, 1],
        ['report_generator', 'রিপোর্ট জেনারেটর', null, 2],
        ['newspaper', 'নিউজপেপার', null, 3],
            ['bangla', 'বাংলা', 'newspaper', 1],
                ['national', 'জাতীয়', 'bangla', 1],
                ['english', 'ইংরেজি', 'bangla', 2],
                ['local', 'লোকাল', 'bangla', 3],
                ['online', 'অনলাইন', 'bangla', 4],
                ['tv', 'টিভি চ্যানেল', 'bangla', 5],
                ['radio', 'রেডিও', 'bangla', 6],
                ['probashi', 'প্রবাসী', 'bangla', 7],
                ['tech', 'টেকনোলজি', 'bangla', 8],
                ['jobs', 'চাকরির খবর', 'bangla', 9],
                ['magazine', 'ম্যাগাজিন', 'bangla', 10],
            ['indian', 'ইন্ডিয়ান', 'newspaper', 2],
                ['indian_nat', 'জাতীয় (বাংলা)', 'indian', 1],
                ['indian_eng', 'ইংরেজি', 'indian', 2],
                ['indian_local', 'লোকাল (কলকাতা/ত্রিপুরা)', 'indian', 3],
            ['pakistan', 'পাকিস্তান', 'newspaper', 3],
                ['pak_eng', 'ইংরেজি (English)', 'pakistan', 1],
                ['pak_urdu', 'উর্দু (Urdu)', 'pakistan', 2],
            ['myanmar', 'মায়ানমার', 'newspaper', 4],
                ['my_national', 'জাতীয়', 'myanmar', 1],
                ['my_english', 'ইংরেজি', 'myanmar', 2],
                ['my_local', 'লোকাল', 'myanmar', 3],
                ['my_online', 'অনলাইন', 'myanmar', 4],
            ['international', 'ইন্টান্যাশনাল', 'newspaper', 5],
        ['facebook', 'ফেসবুক', null, 4],
            ['fb_national', 'জাতীয় সংবাদ (FB)', 'facebook', 1],
            ['fb_online', 'অনলাইন পোর্টাল (FB)', 'facebook', 2],
            ['fb_tv', 'টিভি চ্যানেল (FB)', 'facebook', 3],
            ['fb_radio', 'রেডিও (FB)', 'facebook', 4],
            ['fb_local', 'লোকাল সংবাদ (FB)', 'facebook', 5],
            ['fb_indian', 'ইন্ডিয়ান মিডিয়া (FB)', 'facebook', 6],
            ['fb_pakistan', 'পাকিস্তান মিডিয়া (FB)', 'facebook', 7],
            ['fb_international', 'ইন্টারন্যাশনাল (FB)', 'facebook', 8],
            ['fb_myanmar', 'মায়ানমার মিডিয়া (FB)', 'facebook', 9],
            ['fb_defense', 'প্রতিরক্ষা বাহিনী', 'facebook', 10],
            ['fb_police', 'আইন-শৃঙ্খলা', 'facebook', 11],
            ['fb_govt', 'সরকারি সংস্থা', 'facebook', 12],
            ['fb_pahari', 'পাহাড়ী সংগঠন', 'facebook', 13],
        ['youtube', 'ইউটিউব', null, 5],
            ['yt_news', 'সংবাদ', 'youtube', 1],
            ['yt_entertainment', 'বিনোদন', 'youtube', 2],
            ['yt_tech', 'প্রযুক্তি', 'youtube', 3],
            ['yt_islamic', 'ইসলামিক', 'youtube', 5],
            ['yt_defense', 'প্রতিরক্ষা', 'youtube', 9],
            ['yt_pahari', 'পাহাড়ী', 'youtube', 8],
            ['yt_influencer', 'ইনফ্লুয়েন্সার', 'youtube', 10],
        ['talkshow', 'টকশো', null, 6],
            ['latest_updates', 'লেটেস্ট আপডেট', 'talkshow', 1],
            ['ts_neutral', 'নিরপেক্ষ / মেইনস্ট্রিম', 'talkshow', 2],
            ['ts_awami', 'আওয়ামী পন্থী', 'talkshow', 3],
            ['ts_bnp', 'বিএনপি পন্থী', 'talkshow', 4],
            ['ts_jamaat', 'জামায়াত / ইসলামিক', 'talkshow', 5],
            ['ts_activist', 'অনলাইন অ্যাক্টিভিস্ট', 'talkshow', 6],
            ['ts_army', 'সেনা অফিসার', 'talkshow', 7],
        ['propagandist', 'প্রপাগান্ডিষ্ট', null, 7],
            ['prop_awami', 'আওয়ামী পন্থী', 'propagandist', 1],
            ['prop_bnp', 'বিএনপি পন্থী', 'propagandist', 2],
            ['prop_jamaat', 'জামায়াত পন্থী', 'propagandist', 3],
            ['prop_others', 'অন্যান্য', 'propagandist', 4],
        ['tools', 'টুলস', null, 8],
            ['open_tools', 'টুলস প্যানেল', 'tools', 1],
            ['trend_news', 'ট্রেন্ড নিউজ', 'tools', 3],
            ['phonebook', 'মোবাইল নং', 'tools', 4],
            ['fact_check', 'ফ্যাক্ট চেক', 'tools', 5],
    ],

    // --- 2. LINKS ---
    'links' => [
        // BD National
        ['np_01', 'প্রথম আলো', 'https://www.prothomalo.com', 'newspaper', 'bangla', 'national', 1],
        ['np_02', 'কালের কণ্ঠ', 'https://www.kalerkantho.com', 'newspaper', 'bangla', 'national', 2],
        ['np_03', 'যুগান্তর', 'https://www.jugantor.com', 'newspaper', 'bangla', 'national', 3],
        ['np_04', 'ইত্তেফাক', 'https://www.ittefaq.com.bd', 'newspaper', 'bangla', 'national', 4],
        ['np_05', 'সমকাল', 'https://samakal.com', 'newspaper', 'bangla', 'national', 5],
        ['np_06', 'নয়া দিগন্ত', 'https://www.dailynayadiganta.com', 'newspaper', 'bangla', 'national', 6],
        ['np_07', 'জনকণ্ঠ', 'https://www.dailyjanakantha.com', 'newspaper', 'bangla', 'national', 7],
        ['np_08', 'ইনকিলাব', 'https://www.dailyinqilab.com', 'newspaper', 'bangla', 'national', 8],
        ['np_09', 'মানবজমিন', 'https://mzamin.com', 'newspaper', 'bangla', 'national', 9],
        ['np_10', 'বাংলাদেশ প্রতিদিন', 'https://www.bd-pratidin.com', 'newspaper', 'bangla', 'national', 10],
        ['np_11', 'ভোরের কাগজ', 'https://www.bhorerkagoj.com', 'newspaper', 'bangla', 'national', 11],
        ['np_12', 'আমাদের সময়', 'https://www.dainikamadershomoy.com', 'newspaper', 'bangla', 'national', 12],
        ['np_13', 'যায়যায়দিন', 'https://www.jaijaidinbd.com', 'newspaper', 'bangla', 'national', 13],
        ['np_14', 'সংগ্রাম', 'https://dailysangram.com', 'newspaper', 'bangla', 'national', 14],
        ['np_15', 'সংবাদ', 'https://sangbad.net.bd', 'newspaper', 'bangla', 'national', 15],
        ['np_16', 'বণিক বার্তা', 'https://bonikbarta.net', 'newspaper', 'bangla', 'national', 16],
        ['np_17', 'কালবেলা', 'https://www.kalbela.com', 'newspaper', 'bangla', 'national', 17],
        ['np_18', 'দেশ রূপান্তর', 'https://www.deshrupantor.com', 'newspaper', 'bangla', 'national', 18],
        ['np_19', 'মানবকণ্ঠ', 'https://www.manobkantha.com.bd', 'newspaper', 'bangla', 'national', 19],
        ['np_20', 'আলোকিত বাংলাদেশ', 'https://www.alokitobangladesh.com', 'newspaper', 'bangla', 'national', 20],
        ['np_21', 'ভোরের পাতা', 'https://www.dailyvorerpata.com', 'newspaper', 'bangla', 'national', 21],
        ['np_22', 'খোলা কাগজ', 'https://www.kholakagojbd.com', 'newspaper', 'bangla', 'national', 22],
        ['np_23', 'আমাদের অর্থনীতি', 'https://www.amaderorthoneeti.com', 'newspaper', 'bangla', 'national', 23],
        ['np_24', 'শেয়ার বিজ', 'https://sharebiz.net', 'newspaper', 'bangla', 'national', 24],
        ['np_25', 'প্রতিদিনের সংবাদ', 'https://www.protidinersangbad.com', 'newspaper', 'bangla', 'national', 25],
        ['np_26', 'আজকের পত্রিকা', 'https://www.ajkerpatrika.com', 'newspaper', 'bangla', 'national', 26],
        ['np_27', 'সময়ের আলো', 'https://www.shomoyeralo.com', 'newspaper', 'bangla', 'national', 27],
        ['np_28', 'বাংলাদেশের খবর', 'https://www.bangladesherkhabor.net', 'newspaper', 'bangla', 'national', 28],
        ['np_29', 'আমার সংবাদ', 'https://www.amarsangbad.com', 'newspaper', 'bangla', 'national', 29],
        ['np_30', 'ঢাকা টাইমস', 'https://www.dhakatimes24.com', 'newspaper', 'bangla', 'national', 30],
        ['np_31', 'দৈনিক বাংলা', 'https://www.dainikbangla.com.bd', 'newspaper', 'bangla', 'national', 31],
        ['np_32', 'আজকের দর্পণ', 'https://www.ajkerdarpon.com', 'newspaper', 'bangla', 'national', 32],
        ['np_33', 'সরেজমিন বার্তা', 'https://www.sorejominbarta.com', 'newspaper', 'bangla', 'national', 33],
        ['np_34', 'নবাব', 'https://www.dailynabab.com', 'newspaper', 'bangla', 'national', 34],
        ['np_35', 'সংবাদ সারাবেলা', 'https://www.sangbadsarabela.com', 'newspaper', 'bangla', 'national', 35],
        ['np_36', 'বাংলাদেশ জার্নাল', 'https://www.bd-journal.com', 'newspaper', 'bangla', 'national', 36],
        ['np_37', 'অর্থনীতি প্রতিদিন', 'https://arthoniteeprotidin.com', 'newspaper', 'bangla', 'national', 37],
        ['np_38', 'খবরপত্র', 'https://www.khoborpatra.com', 'newspaper', 'bangla', 'national', 38],
        ['np_39', 'মানবজমিন (English)', 'https://mzamin.com/english', 'newspaper', 'bangla', 'english', 58],
        ['np_40', 'কালব', 'https://kalb.com.bd', 'newspaper', 'bangla', 'national', 40],

        // English Newspapers
        ['eng_01', 'The Daily Star', 'https://www.thedailystar.net', 'newspaper', 'bangla', 'english', 50],
        ['eng_02', 'Dhaka Tribune', 'https://www.dhakatribune.com', 'newspaper', 'bangla', 'english', 51],
        ['eng_03', 'New Age', 'https://www.newagebd.net', 'newspaper', 'bangla', 'english', 52],
        ['eng_04', 'The Independent', 'https://theindependentbd.com', 'newspaper', 'bangla', 'english', 53],
        ['eng_05', 'Daily Sun', 'https://www.daily-sun.com', 'newspaper', 'bangla', 'english', 54],
        ['eng_06', 'The Financial Express', 'https://thefinancialexpress.com.bd', 'newspaper', 'bangla', 'english', 55],
        ['eng_07', 'The Business Standard', 'https://www.tbsnews.net', 'newspaper', 'bangla', 'english', 56],
        ['eng_08', 'Daily Observer', 'https://www.observerbd.com', 'newspaper', 'bangla', 'english', 57],
        ['eng_09', 'The Bangladesh Today', 'https://thebangladeshtoday.com', 'newspaper', 'bangla', 'english', 59],
        ['eng_10', 'Asian Age', 'https://dailyasianage.com', 'newspaper', 'bangla', 'english', 60],
        ['eng_11', 'News Today', 'https://newstoday.com.bd', 'newspaper', 'bangla', 'english', 61],
        ['eng_12', 'Weekly Holiday', 'https://weeklyholiday.net', 'newspaper', 'bangla', 'english', 62],

        // Online Portals
        ['on_01', 'bdnews24', 'https://bangla.bdnews24.com', 'newspaper', 'bangla', 'online', 80],
        ['on_02', 'banglanews24', 'https://www.banglanews24.com', 'newspaper', 'bangla', 'online', 81],
        ['on_03', 'Jagonews24', 'https://www.jagonews24.com', 'newspaper', 'bangla', 'online', 82],
        ['on_04', 'Dhaka Post', 'https://www.dhakapost.com', 'newspaper', 'bangla', 'online', 83],
        ['on_05', 'Rising BD', 'https://www.risingbd.com', 'newspaper', 'bangla', 'online', 84],
        ['on_06', 'Barta24', 'https://barta24.com', 'newspaper', 'bangla', 'online', 85],
        ['on_07', 'Sarabangla', 'https://sarabangla.net', 'newspaper', 'bangla', 'online', 86],
        ['on_08', 'Bangla Tribune', 'https://www.banglatribune.com', 'newspaper', 'bangla', 'online', 87],
        ['on_09', 'The Report24', 'https://www.thereport24.com', 'newspaper', 'bangla', 'online', 88],
        ['on_10', 'Priyo.com', 'https://www.priyo.com', 'newspaper', 'bangla', 'online', 89],
        ['on_11', 'DMP News', 'https://dmpnews.org', 'newspaper', 'bangla', 'online', 90],
        ['on_12', 'Poriborton', 'https://poriborton.com', 'newspaper', 'bangla', 'online', 91],
        ['on_13', 'BdCricTime', 'https://www.bdcrictime.com', 'newspaper', 'bangla', 'online', 92],
        ['on_14', 'Tech Shohor', 'https://techshohor.com', 'newspaper', 'bangla', 'online', 93],
        ['on_15', 'Zoom Bangla', 'https://zoombangla.com', 'newspaper', 'bangla', 'online', 94],
        ['on_17', 'Anyadin', 'https://anyadin.com', 'newspaper', 'bangla', 'online', 96],
        ['on_18', 'Natun Barta', 'https://natunbarta.com', 'newspaper', 'bangla', 'online', 97],
        ['on_19', ' শীর্ষ সংবাদ', 'https://sheershasangbad.com', 'newspaper', 'bangla', 'online', 98],
        ['on_20', 'Breaking News BD', 'https://breakingnews.com.bd', 'newspaper', 'bangla', 'online', 99],

        // TV Channels
        ['tv_01', 'Somoy TV', 'https://www.somoynews.tv', 'newspaper', 'bangla', 'tv', 100],
        ['tv_02', 'Jamuna TV', 'https://www.jamuna.tv', 'newspaper', 'bangla', 'tv', 101],
        ['tv_03', 'Ekattor TV', 'https://ekattor.tv', 'newspaper', 'bangla', 'tv', 102],
        ['tv_04', 'Independent TV', 'https://www.independent24.com', 'newspaper', 'bangla', 'tv', 103],
        ['tv_05', 'Channel i', 'https://www.channelionline.com', 'newspaper', 'bangla', 'tv', 104],
        ['tv_06', 'NTV Online', 'https://www.ntvbd.com', 'newspaper', 'bangla', 'tv', 105],
        ['tv_07', 'RTV Online', 'https://www.rtvonline.com', 'newspaper', 'bangla', 'tv', 106],
        ['tv_08', 'ATN News', 'https://www.atnnewstv.com', 'newspaper', 'bangla', 'tv', 107],
        ['tv_09', 'Channel 24', 'https://www.channel24bd.tv', 'newspaper', 'bangla', 'tv', 108],
        ['tv_10', 'DBC News', 'https://dbcnews.tv', 'newspaper', 'bangla', 'tv', 109],
        ['tv_11', 'News24', 'https://www.news24bd.tv', 'newspaper', 'bangla', 'tv', 110],
        ['tv_12', 'Maasranga TV', 'https://maasranga.tv', 'newspaper', 'bangla', 'tv', 111],
        ['tv_13', 'Boishakhi TV', 'https://www.boishakhionline.com', 'newspaper', 'bangla', 'tv', 112],
        ['tv_14', 'Banglavision', 'https://bvnews24.com', 'newspaper', 'bangla', 'tv', 113],
        ['tv_15', 'Desh TV', 'https://desh.tv', 'newspaper', 'bangla', 'tv', 114],
        ['tv_16', 'GTV (Gazi)', 'https://gaazi.tv', 'newspaper', 'bangla', 'tv', 115],
        ['tv_17', 'SA TV', 'https://satv.tv', 'newspaper', 'bangla', 'tv', 116],
        ['tv_18', 'Mohona TV', 'https://mohona.tv', 'newspaper', 'bangla', 'tv', 117],
        ['tv_19', 'Asian TV', 'https://asiantvbd.tv', 'newspaper', 'bangla', 'tv', 118],
        ['tv_20', 'Bijoy TV', 'https://bijoy.tv', 'newspaper', 'bangla', 'tv', 119],
        ['tv_21', 'Dipto TV', 'https://www.dipto.tv', 'newspaper', 'bangla', 'tv', 120],
        ['tv_22', 'Nagorik TV', 'https://nagorik.com', 'newspaper', 'bangla', 'tv', 121],
        ['tv_23', 'Ekhon TV', 'https://ekhon.tv', 'newspaper', 'bangla', 'tv', 122],
        ['tv_24', 'Global TV', 'https://globaltvbd.com', 'newspaper', 'bangla', 'tv', 123],
        ['tv_25', 'Nexus TV', 'https://nexustelevision.com', 'newspaper', 'bangla', 'tv', 124],
        ['tv_26', 'My TV', 'https://mytvbd.tv', 'newspaper', 'bangla', 'tv', 125],

        // Radio
        ['rad_01', 'Radio Today', 'https://radiotodaybd.fm', 'newspaper', 'bangla', 'radio', 130],
        ['rad_02', 'Radio Foorti', 'https://radiofoorti.fm', 'newspaper', 'bangla', 'radio', 131],
        ['rad_03', 'Dhaka FM', 'https://dhakafm904.com', 'newspaper', 'bangla', 'radio', 132],
        ['rad_04', 'ABC Radio', 'https://abcradio.fm', 'newspaper', 'bangla', 'radio', 133],
        ['rad_05', 'Jago FM', 'https://jago.fm', 'newspaper', 'bangla', 'radio', 134],
        ['rad_06', 'Radio Bhumi', 'https://radiobhumi.fm', 'newspaper', 'bangla', 'radio', 135],
        ['rad_07', 'Bangladesh Betar', 'http://www.betar.gov.bd', 'newspaper', 'bangla', 'radio', 136],
        ['rad_08', 'Peoples Radio', 'https://peoplesradio.fm', 'newspaper', 'bangla', 'radio', 137],
        ['rad_09', 'Radio Next', 'https://radionext.fm', 'newspaper', 'bangla', 'radio', 138],
        ['rad_10', 'Spice FM', 'https://spicefm.bd', 'newspaper', 'bangla', 'radio', 139],

        // Local
        ['loc_ctg_01', 'Dainik Azadi', 'https://dainikazadi.net', 'newspaper', 'bangla', 'local', 150],
        ['loc_ctg_02', 'Dainik Purbokone', 'https://dainikpurbokone.net', 'newspaper', 'bangla', 'local', 151],
        ['loc_ctg_03', 'Suprobhat Bangladesh', 'https://suprobhat.com', 'newspaper', 'bangla', 'local', 152],
        ['loc_ctg_04', 'Coxsbazar News (CBN)', 'https://cbn24.com', 'newspaper', 'bangla', 'local', 153],
        ['loc_syl_01', 'Sylhet View', 'https://www.sylhetview24.com', 'newspaper', 'bangla', 'local', 154],
        ['loc_syl_02', 'Dainik Sylhet', 'https://dainiksylhet.com', 'newspaper', 'bangla', 'local', 155],
        ['loc_khl_01', 'Dainik Purbanchal', 'https://purbanchal.com', 'newspaper', 'bangla', 'local', 156],
        ['loc_khl_02', 'Gramer Kagoj (Jashore)', 'https://gramerkagoj.com', 'newspaper', 'bangla', 'local', 157],
        ['loc_khl_03', 'Mathabhanga (Chuadanga)', 'https://mathabhanga.com', 'newspaper', 'bangla', 'local', 158],
        ['loc_raj_01', 'Sonali Sangbad', 'https://sonalisangbad.com', 'newspaper', 'bangla', 'local', 159],
        ['loc_raj_02', 'Karatoa (Bogra)', 'https://www.karatoa.com.bd', 'newspaper', 'bangla', 'local', 160],
        ['loc_bar_01', 'Barisal Times', 'https://www.barisaltimes.com', 'newspaper', 'bangla', 'local', 161],
        ['loc_rng_01', 'Dainik Karatoa', 'https://karatoa.com.bd', 'newspaper', 'bangla', 'local', 162],
        ['loc_rng_02', 'Uttor Bangla', 'https://uttorbangla.com', 'newspaper', 'bangla', 'local', 163],
        ['loc_cht_01', 'Paharchura', 'https://paharchura.com', 'newspaper', 'bangla', 'local', 164],
        ['loc_cht_02', 'CHT News', 'https://chtnews.blogspot.com', 'newspaper', 'bangla', 'local', 165],

        // Indian
        ['ind_bn_01', 'Anandabazar Patrika', 'https://www.anandabazar.com', 'newspaper', 'indian', 'indian_nat', 200],
        ['ind_bn_02', 'Bartaman', 'https://bartamanpatrika.com', 'newspaper', 'indian', 'indian_nat', 201],
        ['ind_bn_03', 'Sangbad Pratidin', 'https://www.sangbadpratidin.in', 'newspaper', 'indian', 'indian_nat', 202],
        ['ind_bn_04', 'Aajkaal', 'https://www.aajkaal.in', 'newspaper', 'indian', 'indian_nat', 203],
        ['ind_bn_05', 'Ei Samay', 'https://eisamay.com', 'newspaper', 'indian', 'indian_nat', 204],
        ['ind_bn_06', 'Ganashakti', 'https://ganashakti.com', 'newspaper', 'indian', 'indian_nat', 205],
        ['ind_bn_07', 'Puber Kalom', 'https://puberkalom.com', 'newspaper', 'indian', 'indian_nat', 206],
        ['ind_bn_08', 'Uttarbanga Sambad', 'https://uttarbangasambad.com', 'newspaper', 'indian', 'indian_local', 207],
        ['ind_bn_09', 'Syandan Patrika (Tripura)', 'https://syandanpatrika.com', 'newspaper', 'indian', 'indian_local', 208],
        ['ind_bn_10', 'Dainik Sambad (Tripura)', 'https://dainiksambad.com', 'newspaper', 'indian', 'indian_local', 209],
        ['ind_en_01', 'The Hindu', 'https://www.thehindu.com', 'newspaper', 'indian', 'indian_eng', 210],
        ['ind_en_02', 'Times of India', 'https://timesofindia.indiatimes.com', 'newspaper', 'indian', 'indian_eng', 211],
        ['ind_en_03', 'Hindustan Times', 'https://www.hindustantimes.com', 'newspaper', 'indian', 'indian_eng', 212],
        ['ind_en_04', 'NDTV', 'https://www.ndtv.com', 'newspaper', 'indian', 'indian_eng', 213],
        ['ind_en_05', 'Indian Express', 'https://indianexpress.com', 'newspaper', 'indian', 'indian_eng', 214],

        // Pakistan
        ['pak_en_01', 'Dawn', 'https://www.dawn.com', 'newspaper', 'pakistan', 'pak_eng', 250],
        ['pak_en_02', 'The News International', 'https://www.thenews.com.pk', 'newspaper', 'pakistan', 'pak_eng', 251],
        ['pak_en_03', 'The Express Tribune', 'https://tribune.com.pk', 'newspaper', 'pakistan', 'pak_eng', 252],
        ['pak_en_04', 'The Nation', 'https://nation.com.pk', 'newspaper', 'pakistan', 'pak_eng', 253],
        ['pak_en_05', 'Daily Times', 'https://dailytimes.com.pk', 'newspaper', 'pakistan', 'pak_eng', 254],
        ['pak_ur_01', 'Daily Jang', 'https://jang.com.pk', 'newspaper', 'pakistan', 'pak_urdu', 260],
        ['pak_ur_02', 'Daily Express', 'https://www.express.com.pk', 'newspaper', 'pakistan', 'pak_urdu', 261],
        ['pak_ur_03', 'Nawaiwaqt', 'https://www.nawaiwaqt.com.pk', 'newspaper', 'pakistan', 'pak_urdu', 262],
        ['pak_ur_04', 'Dunya News', 'https://dunya.com.pk', 'newspaper', 'pakistan', 'pak_urdu', 263],

        // Myanmar
        ['myn_01', 'The Irrawaddy', 'https://www.irrawaddy.com', 'newspaper', 'myanmar', 'my_english', 300],
        ['myn_02', 'Myanmar Now', 'https://myanmar-now.org', 'newspaper', 'myanmar', 'my_english', 301],
        ['myn_03', 'Mizzima', 'https://www.mizzima.com', 'newspaper', 'myanmar', 'my_english', 302],
        ['myn_04', 'Khit Thit Media', 'https://www.khitthitmedia.org', 'newspaper', 'myanmar', 'my_online', 303],
        ['myn_05', 'Narinjara News', 'https://narinjara.com', 'newspaper', 'myanmar', 'my_local', 304],
        ['myn_06', 'DVB (Democratic Voice of Burma)', 'https://english.dvb.no', 'newspaper', 'myanmar', 'my_online', 305],
        ['myn_07', 'Global New Light of Myanmar', 'https://www.gnlm.com.mm', 'newspaper', 'myanmar', 'my_national', 306],
        ['myn_08', 'Eleven Myanmar', 'https://elevenmyanmar.com', 'newspaper', 'myanmar', 'my_english', 307],
        ['myn_09', 'The Voice', 'https://voice-daily.com', 'newspaper', 'myanmar', 'my_local', 308],
        ['myn_10', 'Karen News', 'https://karennews.org', 'newspaper', 'myanmar', 'my_local', 309],
        ['myn_11', 'Shan News', 'https://english.shannews.org', 'newspaper', 'myanmar', 'my_local', 310],

        // International
        ['int_01', 'BBC News', 'https://www.bbc.com', 'newspaper', 'international', '', 400],
        ['int_02', 'BBC Bangla', 'https://www.bbc.com/bengali', 'newspaper', 'international', '', 401],
        ['int_03', 'CNN', 'https://edition.cnn.com', 'newspaper', 'international', '', 402],
        ['int_04', 'Al Jazeera', 'https://www.aljazeera.com', 'newspaper', 'international', '', 403],
        ['int_05', 'Reuters', 'https://www.reuters.com', 'newspaper', 'international', '', 404],
        ['int_06', 'The Guardian', 'https://www.theguardian.com', 'newspaper', 'international', '', 405],
        ['int_07', 'New York Times', 'https://www.nytimes.com', 'newspaper', 'international', '', 406],
        ['int_08', 'DW (Deutsche Welle)', 'https://www.dw.com', 'newspaper', 'international', '', 407],
        ['int_09', 'VOA Bangla', 'https://www.voabangla.com', 'newspaper', 'international', '', 408],
        ['int_10', 'AFP', 'https://www.afp.com', 'newspaper', 'international', '', 409],
        ['int_11', 'Bloomberg', 'https://www.bloomberg.com', 'newspaper', 'international', '', 410],
        ['int_12', 'Wall Street Journal', 'https://www.wsj.com', 'newspaper', 'international', '', 411],
        ['int_13', 'Washington Post', 'https://www.washingtonpost.com', 'newspaper', 'international', '', 412],
        ['int_14', 'France 24', 'https://www.france24.com', 'newspaper', 'international', '', 413],
        ['int_15', 'RT (Russia Today)', 'https://www.rt.com', 'newspaper', 'international', '', 414],
        ['int_16', 'Xinhua', 'http://www.xinhuanet.com/english', 'newspaper', 'international', '', 415],
        ['int_17', 'TRT World', 'https://www.trtworld.com', 'newspaper', 'international', '', 416],
        ['int_18', 'CNA (Singapore)', 'https://www.channelnewsasia.com', 'newspaper', 'international', '', 417],
        ['int_19', 'NHK World', 'https://www3.nhk.or.jp/nhkworld', 'newspaper', 'international', '', 418],
        ['int_20', 'South China Morning Post', 'https://www.scmp.com', 'newspaper', 'international', '', 419],

        // Facebook Links
        ['fb_np_01', 'Prothom Alo FB', 'https://www.facebook.com/DailyProthomAlo', 'facebook', 'fb_national', '', 1500],
        ['fb_np_02', 'Kaler Kantho FB', 'https://www.facebook.com/kalerkantho', 'facebook', 'fb_national', '', 1501],
        ['fb_np_03', 'Jugantor FB', 'https://www.facebook.com/dainikjugantor', 'facebook', 'fb_national', '', 1502],
        ['fb_np_04', 'Ittefaq FB', 'https://www.facebook.com/dailyittefaq', 'facebook', 'fb_national', '', 1503],
        ['fb_np_05', 'Samakal FB', 'https://www.facebook.com/samakal', 'facebook', 'fb_national', '', 1504],
        ['fb_np_06', 'Naya Diganta FB', 'https://www.facebook.com/dailynayadiganta', 'facebook', 'fb_national', '', 1505],
        ['fb_np_07', 'Janakantha FB', 'https://www.facebook.com/dailyjanakantha', 'facebook', 'fb_national', '', 1506],
        ['fb_np_08', 'Inqilab FB', 'https://www.facebook.com/DailyInqilabOnline', 'facebook', 'fb_national', '', 1507],
        ['fb_np_09', 'Manabzamin FB', 'https://www.facebook.com/dailymanabzamin', 'facebook', 'fb_national', '', 1508],
        ['fb_np_10', 'Bangladesh Pratidin FB', 'https://www.facebook.com/bdpratidin', 'facebook', 'fb_national', '', 1509],
        ['fb_np_11', 'Bhorer Kagoj FB', 'https://www.facebook.com/BhorerKagoj.Live', 'facebook', 'fb_national', '', 1510],
        ['fb_np_12', 'Amader Shomoy FB', 'https://www.facebook.com/dainikamadershomoy', 'facebook', 'fb_national', '', 1511],
        ['fb_np_13', 'Jaijaidin FB', 'https://www.facebook.com/jaijaidinbd', 'facebook', 'fb_national', '', 1512],
        ['fb_np_14', 'Bonik Barta FB', 'https://www.facebook.com/dailybonikbarta', 'facebook', 'fb_national', '', 1513],
        ['fb_np_15', 'Kalbela FB', 'https://www.facebook.com/kalbelaonline', 'facebook', 'fb_national', '', 1514],
        ['fb_np_16', 'Desh Rupantor FB', 'https://www.facebook.com/deshrupantor', 'facebook', 'fb_national', '', 1515],
        ['fb_np_17', 'Daily Star FB', 'https://www.facebook.com/dailystarnews', 'facebook', 'fb_national', '', 1516],
        ['fb_np_18', 'Dhaka Tribune FB', 'https://www.facebook.com/DhakaTribune', 'facebook', 'fb_national', '', 1517],
        ['fb_np_19', 'Business Standard FB', 'https://www.facebook.com/tbsnews.net', 'facebook', 'fb_national', '', 1518],
        ['fb_on_01', 'bdnews24 FB', 'https://www.facebook.com/bdnews24', 'facebook', 'fb_online', '', 1550],
        ['fb_on_02', 'banglanews24 FB', 'https://www.facebook.com/banglanews24', 'facebook', 'fb_online', '', 1551],
        ['fb_on_03', 'Jagonews24 FB', 'https://www.facebook.com/jagonews24', 'facebook', 'fb_online', '', 1552],
        ['fb_on_04', 'Dhaka Post FB', 'https://www.facebook.com/DPostOnline', 'facebook', 'fb_online', '', 1553],
        ['fb_on_05', 'Rising BD FB', 'https://www.facebook.com/Dailyrisingbd', 'facebook', 'fb_online', '', 1554],
        ['fb_on_06', 'Barta24 FB', 'https://www.facebook.com/Barta24BD', 'facebook', 'fb_online', '', 1555],
        ['fb_on_07', 'Sarabangla FB', 'https://www.facebook.com/sarabangla.net', 'facebook', 'fb_online', '', 1556],
        ['fb_on_08', 'Bangla Tribune FB', 'https://www.facebook.com/BanglaTribuneOnline', 'facebook', 'fb_online', '', 1557],
        ['fb_tv_01', 'Somoy TV FB', 'https://www.facebook.com/somoynews.tv', 'facebook', 'fb_tv', '', 1600],
        ['fb_tv_02', 'Jamuna TV FB', 'https://www.facebook.com/JamunaTelevision', 'facebook', 'fb_tv', '', 1601],
        ['fb_tv_03', 'Ekattor TV FB', 'https://www.facebook.com/ekattor.tv', 'facebook', 'fb_tv', '', 1602],
        ['fb_tv_04', 'Independent TV FB', 'https://www.facebook.com/IndependentTVNews', 'facebook', 'fb_tv', '', 1603],
        ['fb_tv_05', 'Channel i FB', 'https://www.facebook.com/channelionline', 'facebook', 'fb_tv', '', 1604],
        ['fb_tv_06', 'NTV FB', 'https://www.facebook.com/ntvdigital', 'facebook', 'fb_tv', '', 1605],
        ['fb_tv_07', 'RTV FB', 'https://www.facebook.com/rtvonline', 'facebook', 'fb_tv', '', 1606],
        ['fb_tv_08', 'ATN News FB', 'https://www.facebook.com/atnnewstv', 'facebook', 'fb_tv', '', 1607],
        ['fb_tv_09', 'Channel 24 FB', 'https://www.facebook.com/channel24bd.tv', 'facebook', 'fb_tv', '', 1608],
        ['fb_tv_10', 'DBC News FB', 'https://www.facebook.com/dbcnews.tv', 'facebook', 'fb_tv', '', 1609],
        ['fb_tv_11', 'News24 FB', 'https://www.facebook.com/news24bd.tv', 'facebook', 'fb_tv', '', 1610],
        ['fb_tv_12', 'Maasranga FB', 'https://www.facebook.com/MaasrangaTelevision', 'facebook', 'fb_tv', '', 1611],
        ['fb_tv_13', 'GTV FB', 'https://www.facebook.com/GaziSatelliteTelevisionLtd', 'facebook', 'fb_tv', '', 1612],
        ['fb_tv_14', 'Desh TV FB', 'https://www.facebook.com/deshtv', 'facebook', 'fb_tv', '', 1613],
        ['fb_tv_15', 'Boishakhi TV FB', 'https://www.facebook.com/boishakhimedia', 'facebook', 'fb_tv', '', 1614],
        ['fb_rad_01', 'Radio Today FB', 'https://www.facebook.com/RadioTodayFM89.6', 'facebook', 'fb_radio', '', 1650],
        ['fb_rad_02', 'Radio Foorti FB', 'https://www.facebook.com/radiofoorti', 'facebook', 'fb_radio', '', 1651],
        ['fb_rad_03', 'Dhaka FM FB', 'https://www.facebook.com/dhakafm90.4', 'facebook', 'fb_radio', '', 1652],
        ['fb_rad_04', 'ABC Radio FB', 'https://www.facebook.com/abcradiofm89.2', 'facebook', 'fb_radio', '', 1653],
        ['fb_rad_05', 'Jago FM FB', 'https://www.facebook.com/jago.fm', 'facebook', 'fb_radio', '', 1654],
        ['fb_rad_06', 'Bangladesh Betar FB', 'https://www.facebook.com/BangladeshBetar.Gov.Bd', 'facebook', 'fb_radio', '', 1655],
        ['fb_rad_07', 'BBC Bangla Radio FB', 'https://www.facebook.com/BBCnewsBangla', 'facebook', 'fb_radio', '', 1656],
        ['fb_loc_01', 'Dainik Azadi FB (CTG)', 'https://www.facebook.com/dainikazadi', 'facebook', 'fb_local', '', 1700],
        ['fb_loc_02', 'Dainik Purbokone FB', 'https://www.facebook.com/dainikpurbokone', 'facebook', 'fb_local', '', 1701],
        ['fb_loc_03', 'Sylhet View FB', 'https://www.facebook.com/sylhetview24', 'facebook', 'fb_local', '', 1702],
        ['fb_loc_04', 'Gramer Kagoj FB (Jashore)', 'https://www.facebook.com/gramerkagoj', 'facebook', 'fb_local', '', 1703],
        ['fb_loc_05', 'Coxsbazar News FB', 'https://www.facebook.com/cbn24', 'facebook', 'fb_local', '', 1704],
        ['fb_loc_06', 'Purbanchal FB (Khulna)', 'https://www.facebook.com/daily-purbanchal', 'facebook', 'fb_local', '', 1705],
        ['fb_ind_01', 'Anandabazar FB', 'https://www.facebook.com/anandabazar.abp', 'facebook', 'fb_indian', '', 1750],
        ['fb_ind_02', '24 Ghanta FB', 'https://www.facebook.com/zeenews', 'facebook', 'fb_indian', '', 1751],
        ['fb_ind_03', 'ABP Ananda FB', 'https://www.facebook.com/abpananda', 'facebook', 'fb_indian', '', 1752],
        ['fb_ind_04', 'The Hindu FB', 'https://www.facebook.com/thehindu', 'facebook', 'fb_indian', '', 1753],
        ['fb_ind_05', 'Times of India FB', 'https://www.facebook.com/TimesofIndia', 'facebook', 'fb_indian', '', 1754],
        ['fb_ind_06', 'NDTV FB', 'https://www.facebook.com/ndtv', 'facebook', 'fb_indian', '', 1755],
        ['fb_ind_07', 'Republic Bangla FB', 'https://www.facebook.com/RepublicBangla', 'facebook', 'fb_indian', '', 1756],
        ['fb_pak_01', 'Dawn News FB', 'https://www.facebook.com/dawn.com', 'facebook', 'fb_pakistan', '', 1780],
        ['fb_pak_02', 'Geo News FB', 'https://www.facebook.com/GeoNews', 'facebook', 'fb_pakistan', '', 1781],
        ['fb_pak_03', 'ARY News FB', 'https://www.facebook.com/arynewsasia', 'facebook', 'fb_pakistan', '', 1782],
        ['fb_pak_04', 'Samaa TV FB', 'https://www.facebook.com/samaatvnews', 'facebook', 'fb_pakistan', '', 1783],
        ['fb_int_01', 'BBC News FB', 'https://www.facebook.com/bbcnews', 'facebook', 'fb_international', '', 1800],
        ['fb_int_02', 'CNN FB', 'https://www.facebook.com/cnn', 'facebook', 'fb_international', '', 1801],
        ['fb_int_03', 'Al Jazeera FB', 'https://www.facebook.com/aljazeera', 'facebook', 'fb_international', '', 1802],
        ['fb_int_04', 'Reuters FB', 'https://www.facebook.com/Reuters', 'facebook', 'fb_international', '', 1803],
        ['fb_int_05', 'DW Bangla FB', 'https://www.facebook.com/dw.bengali', 'facebook', 'fb_international', '', 1804],
        ['fb_myn_01', 'The Irrawaddy FB', 'https://www.facebook.com/theirrawaddy', 'facebook', 'fb_myanmar', '', 1850],
        ['fb_myn_02', 'Myanmar Now FB', 'https://www.facebook.com/myanmarnownews', 'facebook', 'fb_myanmar', '', 1851],
        ['fb_myn_03', 'Mizzima FB', 'https://www.facebook.com/MizzimaDaily', 'facebook', 'fb_myanmar', '', 1852],
        ['fb_myn_04', 'Khit Thit Media FB', 'https://www.facebook.com/khitthitnews', 'facebook', 'fb_myanmar', '', 1853],
        ['fb_myn_05', 'Eleven Media FB', 'https://www.facebook.com/ElevenMediaGroup', 'facebook', 'fb_myanmar', '', 1854],
        ['fb_myn_06', 'DVB FB', 'https://www.facebook.com/DVBTVNews', 'facebook', 'fb_myanmar', '', 1855],
        ['fb_def_01', 'Bangladesh Army', 'https://www.facebook.com/bdarmy.army.mil.bd', 'facebook', 'fb_defense', '', 500],
        ['fb_def_02', 'Bangladesh Navy', 'https://www.facebook.com/BangladeshNavyOfficial', 'facebook', 'fb_defense', '', 501],
        ['fb_def_03', 'Bangladesh Air Force', 'https://www.facebook.com/baf.mil.bd', 'facebook', 'fb_defense', '', 502],
        ['fb_def_04', 'ISPR', 'https://www.facebook.com/ISPR.Bangladesh', 'facebook', 'fb_defense', '', 503],
        ['fb_def_05', 'Border Guard Bangladesh', 'https://www.facebook.com/bgb.gov.bd', 'facebook', 'fb_defense', '', 504],
        ['fb_pol_01', 'Bangladesh Police', 'https://www.facebook.com/BangladeshPoliceOfficialPage', 'facebook', 'fb_police', '', 510],
        ['fb_pol_02', 'RAB', 'https://www.facebook.com/rabonlinemediacell', 'facebook', 'fb_police', '', 511],
        ['fb_pol_03', 'DMP', 'https://www.facebook.com/dmpdhaka', 'facebook', 'fb_police', '', 512],
        ['fb_pol_04', 'Fire Service', 'https://www.facebook.com/fscd.bd', 'facebook', 'fb_police', '', 513],
        ['fb_gov_01', 'ICT Division', 'https://www.facebook.com/ictdivisionbd', 'facebook', 'fb_govt', '', 520],
        ['fb_gov_02', 'Bangladesh Govt', 'https://www.facebook.com/BangladeshGov', 'facebook', 'fb_govt', '', 521],
        ['fb_pah_01', 'Arakan Army (The Way of Rakhita)', 'https://www.facebook.com/TheWayOfRakhita', 'facebook', 'fb_pahari', '', 530],
        ['fb_pah_02', 'UPDF', 'https://www.facebook.com/updf.org', 'facebook', 'fb_pahari', '', 531],
        ['fb_pah_03', 'PCJSS', 'https://www.facebook.com/pcjss.org', 'facebook', 'fb_pahari', '', 532],
        ['fb_pah_04', 'Basherkella', 'https://www.facebook.com/Basherkella.Official', 'facebook', 'fb_online', '', 533],

        // YouTube Links
        ['yt_news_01', 'Somoy TV', 'https://www.youtube.com/@somoynews360', 'youtube', 'yt_news', '', 600],
        ['yt_news_02', 'Jamuna TV', 'https://www.youtube.com/@JamunaTVbd', 'youtube', 'yt_news', '', 601],
        ['yt_news_03', 'Ekattor TV', 'https://www.youtube.com/@ekattor_tv', 'youtube', 'yt_news', '', 602],
        ['yt_news_04', 'Independent TV', 'https://www.youtube.com/@IndependentTelevision', 'youtube', 'yt_news', '', 603],
        ['yt_news_05', 'Channel i News', 'https://www.youtube.com/@ChanneliNews', 'youtube', 'yt_news', '', 604],
        ['yt_news_06', 'ATN News', 'https://www.youtube.com/@atnnewslive', 'youtube', 'yt_news', '', 605],
        ['yt_news_07', 'DBC News', 'https://www.youtube.com/@dbcnews_tv', 'youtube', 'yt_news', '', 606],
        ['yt_news_08', 'News24', 'https://www.youtube.com/@News24tvchannel', 'youtube', 'yt_news', '', 607],
        ['yt_news_09', 'Maasranga TV', 'https://www.youtube.com/@MaasrangaTelevisionNews', 'youtube', 'yt_news', '', 608],
        ['yt_news_10', 'Desh TV', 'https://www.youtube.com/@DeshTVNews', 'youtube', 'yt_news', '', 609],
        ['yt_news_11', 'Channel 24', 'https://www.youtube.com/@Channel24Youtube', 'youtube', 'yt_news', '', 610],
        ['yt_news_12', 'RTV News', 'https://www.youtube.com/@RtvNews', 'youtube', 'yt_news', '', 611],
        ['yt_news_13', 'NTV News', 'https://www.youtube.com/@ntvnewsbd', 'youtube', 'yt_news', '', 612],
        ['yt_ind_01', 'ABP Ananda', 'https://www.youtube.com/@ABPAnanda', 'youtube', 'yt_news', '', 615],
        ['yt_ind_02', 'Zee 24 Ghanta', 'https://www.youtube.com/@Zee24Ghanta', 'youtube', 'yt_news', '', 616],
        ['yt_ind_03', 'Republic Bangla', 'https://www.youtube.com/@RepublicBangla', 'youtube', 'yt_news', '', 617],
        ['yt_ind_04', 'NDTV', 'https://www.youtube.com/@NDTV', 'youtube', 'yt_news', '', 618],
        ['yt_int_01', 'BBC News', 'https://www.youtube.com/@BBCNews', 'youtube', 'yt_news', '', 619],
        ['yt_int_02', 'Al Jazeera', 'https://www.youtube.com/@aljazeera', 'youtube', 'yt_news', '', 620],
        ['yt_int_03', 'DW News', 'https://www.youtube.com/@dwnews', 'youtube', 'yt_news', '', 621],
        ['yt_def_01', 'Bangladesh Army', 'https://www.youtube.com/@BangladeshArmy_official', 'youtube', 'yt_defense', '', 630],
        ['yt_def_02', 'Bangladesh Navy', 'https://www.youtube.com/@BangladeshNavy', 'youtube', 'yt_defense', '', 631],
        ['yt_def_03', 'Bangladesh Air Force', 'https://www.youtube.com/@BangladeshAirForce', 'youtube', 'yt_defense', '', 632],
        ['yt_def_04', 'Border Guard Bangladesh', 'https://www.youtube.com/@BorderGuardBangladesh', 'youtube', 'yt_defense', '', 633],
        ['yt_pah_01', 'Arakan Army Media', 'https://www.youtube.com/@ArakanArmyMedia', 'youtube', 'yt_pahari', '', 640],
        ['yt_pah_02', 'UPDF Media', 'https://www.youtube.com/@UPDFMedia', 'youtube', 'yt_pahari', '', 641],

        // Talkshows
        ['ts_neu_01', 'Tritiyo Matra', 'https://www.youtube.com/@TritiyoMatra', 'talkshow', 'ts_neutral', '', 900],
        ['ts_neu_02', 'Channel i Talkshow', 'https://www.youtube.com/@ChanneliNews', 'talkshow', 'ts_neutral', '', 901],
        ['ts_neu_03', 'ATN News Talkshow', 'https://www.youtube.com/@atnnewslive', 'talkshow', 'ts_neutral', '', 902],
        ['ts_al_01', 'Ekattor TV Talkshow', 'https://www.youtube.com/@ekattor_tv', 'talkshow', 'ts_awami', '', 920],
        ['ts_bnp_01', 'BNP Media Cell', 'https://www.youtube.com/@bnpmediacell', 'talkshow', 'ts_bnp', '', 940],
        ['ts_act_02', 'Pinaki Bhattacharya', 'https://www.youtube.com/@PinakiBhattacharya', 'talkshow', 'ts_activist', '', 981],
        ['ts_act_03', 'Elias Hossain', 'https://www.youtube.com/@EliasHossain', 'talkshow', 'ts_activist', '', 982],
        ['ts_act_04', 'Konak Sarwar', 'https://www.youtube.com/@KonakSarwar', 'talkshow', 'ts_activist', '', 983],
        ['ts_act_06', 'Netra News', 'https://www.youtube.com/@NetraNews', 'talkshow', 'ts_activist', '', 985],
    ],

    // --- 3. PHONE DIRECTORY ---
    'phones' => [
        // Emergency
        ['em_999', 'জাতীয় জরুরি সেবা', 'National Emergency Service', 'Hotline', '999', '', 'Emergency', ''],
        ['em_333', 'জাতীয় তথ্য বাতায়ন', 'National Call Center', 'Hotline', '333', '', 'Emergency', ''],
        ['em_109', 'নারী ও শিশু নির্যাতন প্রতিরোধ', 'Women & Children Helpline', 'Hotline', '109', '', 'Emergency', ''],
        ['em_106', 'দুদক অভিযোগ কেন্দ্র', 'ACC Hotline', 'Hotline', '106', '', 'Emergency', ''],
        ['em_1090', 'দুর্যোগের আগাম বার্তা', 'Disaster Warning', 'Hotline', '1090', '', 'Emergency', ''],
        ['em_16263', 'স্বাস্থ্য বাতায়ন', 'Health Call Center', 'Hotline', '16263', '', 'Emergency', ''],
        
        // Police & RAB
        ['pol_dmp', 'ডিএমপি সদরদপ্তর', 'DMP Headquarters', 'Control Room', '01713373127', 'dmp@police.gov.bd', 'Police', 'Dhaka'],
        ['pol_rab', 'র‌্যাব সদরদপ্তর', 'RAB Headquarters', 'Control Room', '01777720029', '', 'Police', 'Dhaka'],
        ['pol_cyber', 'সাইবার পুলিশ সেন্টার', 'Cyber Police Center', 'Hotline', '01320002020', 'cyberhelp@police.gov.bd', 'Police', 'Dhaka'],
        ['pol_highway', 'হাইওয়ে পুলিশ', 'Highway Police', 'Control Room', '01320182595', '', 'Police', 'Dhaka'],
        ['pol_999', 'জরুরি পুলিশ সহায়তা', 'Emergency Police', 'Hotline', '999', '', 'Police', ''],

        // Fire Service
        ['fire_hq', 'ফায়ার সার্ভিস সদরদপ্তর', 'Fire Service HQ', 'Control Room', '01730336699', '', 'Fire Service', 'Dhaka'],
        ['fire_ctg', 'ফায়ার সার্ভিস চট্টগ্রাম', 'Fire Service CTG', 'Control Room', '01730336655', '', 'Fire Service', 'Chittagong'],

        // Hospitals
        ['hosp_dmch', 'ঢাকা মেডিকেল কলেজ', 'DMCH', 'Director', '02-55165088', 'dmch@hospi.dghs.gov.bd', 'Health', 'Dhaka'],
        ['hosp_bsmmu', 'পিজি হাসপাতাল (BSMMU)', 'BSMMU', 'Reception', '02-9661051', '', 'Health', 'Dhaka'],
        ['hosp_kurmitola', 'কুর্মিটোলা জেনারেল হাসপাতাল', 'Kurmitola General Hospital', 'Director', '02-8714479', '', 'Health', 'Dhaka'],
        ['hosp_square', 'স্কয়ার হাসপাতাল', 'Square Hospital', 'Hotline', '10616', '', 'Health', 'Dhaka'],
        ['hosp_united', 'ইউনাইটেড হাসপাতাল', 'United Hospital', 'Hotline', '10666', '', 'Health', 'Dhaka'],
        ['hosp_evercare', 'এভারকেয়ার হাসপাতাল', 'Evercare Hospital', 'Hotline', '10678', '', 'Health', 'Dhaka'],
        
        // Administration
        ['dc_dhaka', 'জেলা প্রশাসক, ঢাকা', 'DC Dhaka', 'DC', '01711546666', 'dcdhaka@mopa.gov.bd', 'Administration', 'Dhaka'],
        ['dc_ctg', 'জেলা প্রশাসক, চট্টগ্রাম', 'DC Chittagong', 'DC', '01713104332', 'dcchittagong@mopa.gov.bd', 'Administration', 'Chittagong'],
        ['uno_savar', 'ইউএনও, সাভার', 'UNO Savar', 'UNO', '01713303830', 'unosavar@mopa.gov.bd', 'Administration', 'Dhaka'],
    ]
];
?>
